package EncounterManager.Resources;

public enum Source{
	PLAYERSHANDBOOK,
	MONSTERMANUAL,
	DUNGEONMASTERSGUIDE,
	
	VOLOSGUIDETOMONSTERS,
	MORDENKAINENSTOMEOFFOES,
	XANATHARSGUIDETOEVERYTHING,
	SWORDCOASTADVENTURERSGUIDE,
		
	CURSEOFSTRAHD,
	GUILDMASTERSGUIDETORAVNICA,
	HOARDOFTHEDRAGONQUEEN,
	LOSTLABORATORYOFKWALISH,
	LOSTMINEOFPHANDELVER,
	OUTOFTHEABYSS,
	PRINCESOFTHEAPOCALYPSE,
	STORMKINGSTHUNDER,
	THERISEOFTIAMAT,
	TALESFROMTHEYAWNINGPORTAL,
	TOMBOFANNIHILATION,
	WATERDEEPDRAGONHEIST,
	WATERDEEPDUNGEONOFTHEMADMAGE,
	
	HUNTERSMARK,
	KARTHUNLANDSOFCONFLICT,
	STRONGHOLDSANDFOLLOWERS,
	TALDOREICAMPAIGNSETTING,
	
	CUSTOM;
}
